# Generated by Django 6.0.2 on 2026-03-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_is_geo_verified_activity_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_points_awarded',
            field=models.BooleanField(default=False, help_text="True when points for this activity have been added to the user's total score."),
        ),
    ]
